# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: light #light/dark

default_redirection_url: https://auth.kqgyl.com # where to redirect for a non-existent URL，一般填 authelia 的完整域名，有端口也要带上

server:
  address: 'tcp://:9091/'
  disable_healthcheck: false

  tls:
    key: ""
    certificate: ""

  buffers:
    read: 4096
    write: 4096

  endpoints:
   enable_pprof: false
   enable_expvars: false



log:
  level: debug



totp:
  issuer: kqgyl.com #your authelia top-level domain，这里不要带端口
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: '5m'
  file:
    path: /authelia_config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: "auth.kqgyl.com" #This should be your authentication URL，这里不要带端口
      policy: bypass
    - domain: "ad.onekartoffel.cn" #example domain to protect，这里不要带端口
      policy: one_factor
    - domain: "nas.onekartoffel.cn" #example subdomain to protect，这里不要带端口
      policy: two_factor

session:
  secret: 'insecure_session_secret'
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'kqgyl.com'
      authelia_url: 'https://auth.kqgyl.com'
      default_redirection_url: 'https://wiki.kqgyl.com'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'

regulation:
  max_retries: 3
  find_time: '2m'
  ban_time: '5m'

storage:
  encryption_key: 'e0173e85841931ba4f2f1009e834fb512aee9a0ecc33a6e2e9ce8a59cf06ee76' #用于加密数据库的随机值，大于12位
  local:
    path: /authelia_config/db.sqlite3 #sqlite3数据库，也可以使用 MySQL.
 

notifier:
  ## You can disable the notifier startup check by setting this to true.
  disable_startup_check: false
  smtp:
    address: 'smtp://127.0.0.1:25'    # 邮件 SMTP 服务器地址+端口
    timeout: '5s'              # 超时
    username: 'test'                  # 用户名
    password: 'password'              # 密码
    sender: 'Authelia <admin@example.com>'
    identifier: 'localhost'
    subject: '[Authelia] {title}'
    startup_check_address: 'test@authelia.com'
    disable_require_tls: false
    disable_html_emails: false

    tls:
      skip_verify: false
      minimum_version: TLS1.2



identity_validation:
  reset_password:
    jwt_lifespan: '5m'
    jwt_algorithm: 'HS256'
    jwt_secret: 'c41609c95e7f07e35f6d8acde082b4eabf191545aa5af541ddc531c76fd41f04'



identity_providers:
  oidc:
    hmac_secret: '9fe25779569b7d30754e8355de25a70482ccabb174e054d160e07eb46e606350'
    jwks:
      key_id: 'example'
      algorithm: 'RS256'
      use: 'sig'
      key: |
        -----BEGIN PRIVATE KEY-----
        MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAL6OzgqI7I5OtBuW
        /HFux70fGUoyRNsJhq5w2qBuz/WnDG9ieSBoDysBAWK9b1kJlkl6eDA+UmbmIEZ/
        cmi1vw1cVm7Hrfcihuw7REMz4sg7K1FQNtiZya5Q86qoBT5xTS/B/Dr1+TJ1S3nq
        OuTGSr+XcnyN2RUCVhQHyd2D5F7XAgMBAAECgYA+erQz4BEv175WDXtX9eqnp7qz
        CShqaQUvzPDiCXNGKC97ld4BMh1HDF1X8qS/nNUZ4n3l04lRE8MhWkg47N5nASfK
        3AywfFIXHGmS7h7RnFm8aeIq+oa77KNcdnRW0y166YOwyPcXWdbYflWn0sX6X/dc
        qWt/kY4D0ckfJJzJAQJBAPlgCA5zBlAC6tEruumiOrZfCg2vWUE516ToYOYnbJym
        1QhKJZXR6XDcLtIqlt+uCCmBaJWBGuE0ZmA3Sm1dpskCQQDDnsOzCl/YZOTW7jkX
        huThHM4soAd8kXouoD40CYDrSDY754ZC5SMSwKjQ/DdOtz8UI9KULAcgZdsGJ9FB
        p4ifAkEA21xHGfbCmcVHK4JNI9Ep1lyZqloRqFeqQoyLGEmbt9zlTipzD2wb7cQx
        h3whRVeAJIqKJeDwdSOz3nUkijm0SQJALzoPKRRiG04QaUtOAT4R178qj197Lzm3
        87XADrQUqbjfTwsQQOos04QrvXiGqbxXwDb9ycPvXIT6obvPKziVJQJALahdgX2B
        B+ijok8BtsnTPNVYMvLm+XvfQanOsQ+Lp5rK228ZqIW7mr/J9ERaBDlALZse0Lv8
        pQzupy1X+n+lww==
        -----END PRIVATE KEY-----

    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
      custom:
        lifespan_name:
          access_token: '1h'
          authorize_code: '1m'
          id_token: '1h'
          refresh_token: '90m'
          grants:
            authorize_code:
              access_token: '1h'
              authorize_code: '1m'
              id_token: '1h'
              refresh_token: '90m'
            implicit:
              access_token: '1h'
              authorize_code: '1m'
              id_token: '1h'
              refresh_token: '90m'
            client_credentials:
              access_token: '1h'
              authorize_code: '1m'
              id_token: '1h'
              refresh_token: '90m'
            refresh_token:
              access_token: '1h'
              authorize_code: '1m'
              id_token: '1h'
              refresh_token: '90m'
            jwt_bearer:
              access_token: '1h'
              authorize_code: '1m'
              id_token: '1h'
              refresh_token: '90m'

    enable_client_debug_messages: false

    clients:
      - client_id: 'outline'       # 这里的 'outline' 是客户端的唯一键 
        client_name: 'Outline Wiki'
        client_secret: '856d53b8eb53c6d4e30194a2'
        public: false
        redirect_uris:
          - https://wiki.kqgyl.com/oauth2/callback
        audience: []
        scopes:
          - 'openid'
          - 'groups'
          - 'email'
          - 'profile'
        grant_types:
          - 'refresh_token'
          - 'authorization_code'
        response_types:
          - 'code'
        response_modes:
          - 'form_post'
          - 'query'
        authorization_policy: 'one_factor'
        userinfo_signed_response_alg: 'none'